<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Асинхронный запрос
	 * Request for putting an authorization hold on the payment amount in the payer's account in batch mode.
	 * 
 */
class AsyncRequest
{
	/**
	 * Ид асинхронного запроса
	 * ID of the asynchronous request
	 * 
	 *
	 * @var int
	 */
	public $asyncId = null;

	/**
	 * Url который будет вызван, после завершения асинхронной задачи
	 * The url that will be called after the asynchronous task is completed
	 * 
	 *
	 * @var string
	 */
	public $callbackUrl = null;
}
