<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос SimplifiedIdentificationRequest.
	 * Response to SimplifiedIdentificationRequest.
	 * 
 */
class SimplifiedIdentificationResponse
{
	
	/**
	 * Если идентификация пользователя прошла успешно, то данный элемент содержит текущие данные пользователя.
	 * If user identification is successful, this element contains user information.
	 * 
	 *
	 * @var PersonalInformation
	 */
	 public $personalInformation = null;

}
